import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import GlobalStyles from "@/app/Globals.module.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Civil Servant Warrior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
      </head>
      <body className={`${GlobalStyles["default"]} text-xs md:text-sm`}>
        {children}
      </body>
    </html>
  );
}
